# Generated by Django 3.1 on 2021-03-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_url',
            field=models.URLField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
