# Generated by Django 3.1 on 2021-03-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=300)),
                ('event_pic', models.URLField()),
                ('seat_limit', models.PositiveIntegerField()),
                ('registered_num', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
                ('begins_on', models.DateTimeField()),
                ('ends_on', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
