# Generated by Django 3.1 on 2021-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='begins_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='ends_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
