# Generated by Django 3.1 on 2021-03-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210316_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='event_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
