# Generated by Django 3.1 on 2021-03-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20210316_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='begins_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='ends_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='event_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='seat_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
